name: GitHub actions - Trigger Jenkins Job
run-name: Trigger Jenkins Job

on:
  push:
    branches: ["main"]

env:
  owner_name: Venkatesh

jobs:
  build_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Job Info
      run: echo "Job build_test is executing as part of new workflow - from $owner_name"

    - uses: actions/checkout@v4

    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.7.0
      with:
        checkout-fetch-depth: 0
        java-version: 17
        java-distribution: temurin
        maven-version: 3.9.8
    - name: Test with Maven
      run: mvn -B test --file pom.xml
    
    - name: connect to LAb and trigger jenkins job
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest 
      with:
        host: ${{ secrets.LAB_HOSTNAME }}
        user: ${{ secrets.LAB_USERNAME }}
        pass: ${{ secrets.LAB_PASSWORD }}
        port: ${{ secrets.LAB_PORT }}
        connect_timeout: 10s 
        first_ssh: |
          sudo curl -I -u admin:1128f58893d52bc7a6ca11e137806f0a45 http://localhost:8080/job/Tomcat%20Apache%20for%20CD/build?token=Project_Token
